# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: jupyter-nb-to-markdown
        name: jupyter-nb-to-markdown
        files: .ipynb
        stages: [commit]
        language: system
        entry: jupyter nbconvert --to markdown
    -   id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: .ipynb
        stages: [commit]
        language: system
        entry: jupyter nbconvert --clear-output --inplace
-   repo: local
    hooks:
    -   id: re-add updated tracked files
        name: re-add updated tracked files
        stages: [commit]
        language: system
        entry: git add -u
