# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://gitlab.com/iamlikeme/nbhooks
    rev: 1.0.0
    hooks:
    -   id: nb-ensure-clean
        args: [--meta, ExecuteTime, 'Clase-*']
#-   repo: https://github.com/mwouts/jupytext
#    rev: v1.13.7
#    hooks:
#    -   id: jupytext
#        args: [--from, ipynb, --to, "markdown"]
