
title: Seminario sobre Gramáticas Formales
description: Material para el el seminario de Gramáticas Formales de la carrera de Letras de la UBA

#theme: jekyll-theme-midnight
theme: jekyll-theme-cayman
show_downloads: "true"